### ISSUE TITLE
Thanks for your interest! Please consider adding RecNN to your list...

### ISSUE THREAD

**Issue by awarebayes** [jihoo-kim/awesome-RecSys#1]
Hi, I've just noticed you starring my reinforced recommendation project on github.
If that would not bother you, please consider adding my library to this list:

### 5. GitHub Repositories
...

- [RecNN](https://github.com/awarebayes/RecNN)(Pytorch Library, Papers)

...

**Comment by jihoo-kim** [comment]
Thanks for your feedback. I'm going to add it:)

**Comment by awarebayes** [comment]
Thanks!
